### PR TITLE
Log status about upgrade to events

### PR DESCRIPTION
**Pull request by machacekondra**
This PR add 5 event messages to cluster upgrade proccess:
1) Log start of upgrade
2) Log there are no hosts to be updated
3) Log which hosts will be updated
4) Log that upgrade failed
5) Log that upgrade finished successfully

Fixes: https://github.com/oVirt/ovirt-ansible-cluster-upgrade/issues/38

https://bugzilla.redhat.com/show_bug.cgi?id=1664844

### CODE REVIEW

**Comment by machacekondra** [comment]
@mwperina

**Comment by machacekondra** [comment]
image

image

**Review by mwperina — APPROVED** [review]

**Comment by gregsheremeta** [comment]
@machacekondra we originally talked about jobs (aka tasks) instead of events. Did that not work out?

**Comment by machacekondra** [comment]
@gregsheremeta I can work on that as well. This patch adds events. And we can add also a task.

**Pull request merged**
